// <auto-generated />
using BankAccountNumberRegistry.Projections.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankAccountNumberRegistry.Projections.Api.Migrations
{
    [DbContext(typeof(ApiProjectionsContext))]
    partial class ApiProjectionsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankAccountNumberRegistry.Projections.Api.OrganisationList.OrganisationList", b =>
                {
                    b.Property<string>("OvoNumber")
                        .ValueGeneratedOnAdd();

                    b.HasKey("OvoNumber")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("OrganisationList","Api");
                });

            modelBuilder.Entity("Be.Vlaanderen.Basisregisters.ProjectionHandling.Runner.ProjectionStates.ProjectionStateItem", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Position");

                    b.HasKey("Name")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("ProjectionStates","Api");
                });
#pragma warning restore 612, 618
        }
    }
}
